server {
    listen 80;
    server_name poseread.liang-lib.tech;

    root /var/www/mediapipe-live-skeleton-demo;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico)$ {
        expires 7d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }

    location ~* \.(wasm|task)$ {
        expires 30d;
        add_header Cache-Control "public";
        types {
            application/wasm wasm;
            application/octet-stream task;
        }
        try_files $uri =404;
    }
}
